groups:
    - groupa
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::disable_front_row
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_show_all_files
        # - osxdefaults::finder_show_status_bar
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::set_desktop_picture
        - osxdefaults::set_screensaver_preferences
        - osxdefaults::turn_off_keyboard_illumination_when_computer_is_not_used_for_5_minutes
        # - osxdefaults::use_name_and_password_on_loginscreen

attributes:
    osxdefaults:
        computername: thea
        desktop_picture: https://ia600401.us.archive.org/19/items/RubyOnAcidWallpapers2009-10-27/00791.jpg
        finder:
            preferred_view_style: Nlsv
    # authorization:
    #     sudo:
    #         users:
    #             - jay
    #         passwordless: true
    #         include_sudoers_d: true
    git:
        name: Jay McGavren
        # email: me@example.com
    homebrewalt:
        apps:
            # - ack
            # - android-ndk
            # - android-platform-tools
            # - android-sdk
            # - apktool
            # - app-engine-java-sdk
            # - ascii
            # - autojump
            # - automake
            # - autotrace
            # - aws-cfn-tools
            # - aws-cloudsearch
            # - aws-elasticache
            # - aws-elasticbeanstalk
            # - aws-sns-cli
            # - awscli
            - bats
            # - bgrep
            # - boot2docker
            # - box2d
            # - bullet
            # - cdrdao
            # - cdrtools
            # - cheat
            # - chrome-cli
            # - chromedriver
            # - clisp
            # - clojurescript
            # - cmake
            # - colordiff
            - cowsay
            - ctags
            - curl
            # - dart
            # - dict
            - docker
            - dos2unix
            # - elixir-build
            # - elixir
            # - emacs-clang-complete-async
            # - emacs # Duplicate from cask-apps?
            # - erlang
            # - exif
            # - exiftags
            # - exiftool
            - ffmpeg
            # - findbugs
            # - findutils
            # - flac
            - fortune
            # - fsh
            # - gawk
            # - gcc
            # - getmail
            # - ghostscript
            - gist
            # - gistit
            # - git-annex
            # - git-archive-all
            # - git-cal
            # - git-cola
            # - git-crypt
            # - git-encrypt
            - git-extras
            # - git-flow-avh
            # - git-flow-clone
            # - git-flow
            # - git-ftp
            # - git-gerrit
            # - git-imerge
            # - git-integration
            # - git-multipush
            # - git-now
            # - git-number
            # - git-open
            # - git-sh
            # - git-ssh
            # - git-tf
            # - git-tracker
            # - git-url-sub
            - git
            # - gitbucket
            # - giter8
            # - github-release
            # - gitslave
            # - gnu-sed
            # - gnu-smalltalk
            # - gnu-tar
            # - gnu-which
            # - gnupg-pkcs11-scd
            # - gnupg
            # - gnupg2
            # - gnuplot
            # - go-app-engine-32
            # - go-app-engine-64
            # - go
            # - google-app-engine
            # - google-perftools
            # - gosu
            # - graphviz
            # - gstreamer
            # - gtk+
            # - gtk+3
            # - gtk-chtheme
            # - gtk-doc
            # - gtk-engines
            # - gtk-gnutella
            # - gtk-murrine-engine
            # - gtkdatabox
            # - gtkglarea
            # - gtkglext
            # - gtkmm
            # - gtkmm3
            # - gtkwave
            # - haproxy
            # - haskell-platform
            # - horndis # Duplicate from cask-apps?
            # - hugo
            # - id3lib
            # - id3tool
            # - id3v2
            # - imagemagick
            # - inkscape
            # - jenkins
            # - jpeg-turbo
            # - jpeg
            # - jpeginfo
            # - jpegoptim
            # - jruby
            # - libav
            # - libdvdcss
            # - libdvdnav
            # - libdvdread
            # - libgit2
            # - libid3tag
            # - libmemcached
            # - libmp3splt
            # - libmpeg2
            # - libmusicbrainz
            # - liboauth
            # - libogg
            # - libquicktime
            # - libraw
            # - librsync
            # - libsass
            # - libssh
            # - libssh2
            # - libusb-compat
            # - libusb
            # - libvorbis
            # - libxml2
            # - libxslt
            # - libyaml
            # - lighttpd
            # - lolcode
            # - lorem
            # - lua
            # - luabind
            # - luajit
            # - luarocks
            - lynx
            # - memcache-top
            - memcached
            # - memcacheq
            # - memtester
            # - midicsv
            # - mp3info
            # - mp3splt
            # - mp4v2
            # - mysql++
            # - mysql-cluster
            # - mysql-connector-c++
            # - mysql-connector-c
            # - mysql-connector-odbc
            # - mysql-proxy
            # - mysql-search-replace
            - mysql
            # - mysqlreport
            - netcat
            # - nginx
            # - ngrep
            # - node
            # - nodebrew
            # - nodenv
            # - ntfs-3g
            # - objc-run
            # - oniguruma
            # - osxfuse
            - phantomjs
            # - pow
            # - psutils
            # - python
            - python3
            # - rbenv-aliases
            # - rbenv-binstubs
            # - rbenv-bundler
            # - rbenv-communal-gems
            # - rbenv-ctags
            # - rbenv-default-gems
            # - rbenv-gem-rehash
            # - rbenv-gemset
            # - rbenv-readline
            # - rbenv-use
            # - rbenv-vars
            # - rbenv-whatis
            # - rbenv
            - redis
            # - rename
            # - renameutils
            # - riak
            # - ruby-build
            # - ruby-install
            # - ruby
            # - runit
            # - rush
            # - sdl
            # - sdl2
            # - sdl2_gfx
            # - sdl2_image
            # - sdl2_mixer
            # - sdl2_net
            # - sdl2_ttf
            # - sdl_gfx
            # - sdl_image
            # - sdl_mixer
            # - sdl_net
            # - sdl_rtf
            # - sdl_sound
            # - sdl_ttf
            # - tcptrace
            # - tcptraceroute
            # - the_platinum_searcher
            - the_silver_searcher
            - tmux
            # - tokyo-cabinet
            # - tor
            - ttyrec
            # - vim
            # - wakeonlan
            - watch
            - wget
            # - wine
            # - wireshark
            # - wordplay
            # - youtube-dl
            # - zeromq
            # - zsh-completions
            # - zsh-history-substring-search
            # - zsh-lovers
            # - zsh-syntax-highlighting
            # - zsh
            # - zshdb
        cask_apps:
            - adobe-reader
            - amazon-music
            - anki
            - audacity
            - bettertouchtool
            - celestia
            - desmume
            - dosbox
            - dropbox
            # - dwarf-fortress
            # - electric-sheep
            - emacs
            - gimp
            - gitx
            - google-drive
            - google-earth
            - handbrake
            - handbrakecli
            - hipchat
            - horndis
            - jumpcut
            - kid3
            - libreoffice
            - onepassword
            - vagrant
            # - mac-informer
            # - mac-linux-usb-loader
            # - macaw
            # - macbreakz
            # - macdown
            # - macdrops
            # - macfusion
            # - macgdbp
            - mame
            # - menumeters # No recipe available.
            - minecraft
            - nethackcocoa
            - node
            # - noiz2sa
            - omnidazzle
            - phantomjs
            # - picasa
            # - postgres
            # - prezi
            # - processing
            - r
            - rescuetime
            # - rrootage
            - screenflow
            - screenhero
            # - scummvm
            - sequel-pro
            # - sketchup
            - skype
            - slate
            - snes9x
            # - soundflower
            - sqlite-database-browser
            # - steam
            - stella
            - sublime-text
            - teeworlds
            # - torbrowser
            - totalterminal
            # - tower
            # - transmit
            # - unity-web-player
            # - unity3d
            - vagrant
            - virtualbox
            - vlc
            # - wesnoth
            # - wireshark
            - xaos
            - xbox360-controller-driver
            # - xscreensaver
